name: LobbyPluginV1
version: '${project.version}'
main: org.caique.lobbypluginv1.Lobbypluginv1
api-version: '1.21'
author: Caique
description: Plugin de Lobby para Minecraft 1.21 com sistema completo

commands:
  login:
    description: Fazer login na conta
    usage: /login <senha>
    aliases: [l]

  register:
    description: Criar uma nova conta
    usage: /register <senha> <confirmar_senha>
    aliases: [reg]

  amigos:
    description: Sistema de amigos
    usage: /amigos <listar|add|remove|aceitar|recusar> [nick]
    aliases: [friends, friend]

  tags:
    description: Ver suas tags disponíveis
    usage: /tags

  tag:
    description: Gerenciar suas tags
    usage: /tag <set|preview|list> [id]

  nametagtest:
    description: Testar sistema de nametags
    usage: /nametagtest [force]
    permission: op

permissions:
  lobby.auth.bypass:
    description: Bypass do sistema de autenticação
    default: false

  lobby.friends.admin:
    description: Permissões administrativas do sistema de amigos
    default: op

  lobby.tag.membro:
    description: Tag de Membro
    default: true

  lobby.tag.ajudante:
    description: Tag de Ajudante
    default: false

  lobby.tag.moderador:
    description: Tag de Moderador
    default: false

  lobby.tag.admin:
    description: Tag de Admin
    default: false

  lobby.tag.gerente:
    description: Tag de Gerente
    default: false

  lobby.tag.master:
    description: Tag de Master
    default: false